security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_MANAGER, ROLE_COACH, ROLE_ATHLETE]
        ROLE_MANAGER:     [ROLE_COACH, ROLE_ATHLETE]
        ROLE_COACH:       [ROLE_ATHLETE]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home_page
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/utilisateur/new$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/$, roles: PUBLIC_ACCESS }  # Public access to root path
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }  # All other paths require auth