# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\GenerateEntitiesCommand:
        tags: [ console.command ]

    App\Command\GenerateRepositoriesCommand:
        tags: [ console.command ]

    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        public: false
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ExerciseApiService:
        arguments:
            $apiKey: '%env(EXERCISE_API_KEY)%'
            $apiHost: '%env(EXERCISE_API_HOST)%'

    App\Service\UserActionLogger:
        arguments:
            $userActionLogger: '@monolog.logger.user_action'
            $tokenStorage: '@security.token_storage'